// client/src/pages/PrepaidIncome.jsx
import React, { useState } from 'react';
import { PiggyBank, ArrowRight, History, Calendar } from 'lucide-react';

const MONTHS = Array.from({ length: 12 }, (_, i) => i + 1);

function PrepaidIncome({ records, loading }) {
    const currentYear = new Date().getFullYear().toString();
    const currentMonth = (new Date().getMonth() + 1).toString();

    const [selectedYear, setSelectedYear] = useState(currentYear);
    const [selectedMonth, setSelectedMonth] = useState(currentMonth);

    if (loading) {
        return <div style={{ textAlign: 'center', padding: '3rem' }}>載入中...</div>;
    }

    // Minguo Calendar Helpers
    const toMinguoYear = (adYear) => parseInt(adYear) - 1911;
    const toMinguoDate = (adDateStr) => {
        if (!adDateStr) return '';
        const [y, m, d] = adDateStr.split('-');
        return `${toMinguoYear(y)}-${m}-${d}`;
    };
    const toMinguoMonth = (adMonthStr) => {
        if (!adMonthStr || !adMonthStr.includes('-')) return adMonthStr;
        const [y, m] = adMonthStr.split('-');
        return `${toMinguoYear(y)}-${m}`;
    };

    // Helper to parse "X-Y月"
    const parsePeriod = (itemName) => {
        const match = itemName.match(/(\d+)-(\d+)月/);
        if (match) {
            return { start: parseInt(match[1]), end: parseInt(match[2]) };
        }
        return null;
    };

    // Helper to calculate total months in a range
    const getTotalMonthsInRange = (startP, endP) => {
        if (!startP || !endP) return 1;
        if (startP.includes('-')) {
            const [sY, sM] = startP.split('-').map(Number);
            const [eY, eM] = endP.split('-').map(Number);
            return (eY - sY) * 12 + (eM - sM) + 1;
        }
        return parseInt(endP) - parseInt(startP) + 1;
    };

    // Helper to calculate recognized months relative to target dashboard date
    const getRecognizedMonths = (targetY, targetM, startP, endP, recordDate) => {
        if (!startP || !endP) return 0;

        const targetStr = `${targetY}-${targetM.toString().padStart(2, '0')}`;
        const totalMonths = getTotalMonthsInRange(startP, endP);

        if (startP.includes('-')) {
            // YYYY-MM format
            if (targetStr < startP) return 0;
            if (targetStr >= endP) return totalMonths;

            // Calculate months from start to target
            const [sY, sM] = startP.split('-').map(Number);
            return (targetY - sY) * 12 + (targetM - sM) + 1;
        } else {
            // Legacy month-only format
            const recordYear = parseInt(recordDate.split('-')[0]);
            if (targetY < recordYear) return 0;
            if (targetY > recordYear) return totalMonths;

            const startM = parseInt(startP);
            const endM = parseInt(endP);
            return Math.max(0, Math.min(totalMonths, targetM - startM + 1));
        }
    };

    const targetYear = parseInt(selectedYear);
    const targetMonth = parseInt(selectedMonth);

    const prepaidRecords = [];
    let totalPrepaidLiability = 0;

    records.filter(r => r.type === 'income').forEach(record => {
        // Priority to explicit YYYY-MM periods
        let startP = record.startPeriod;
        let endP = record.endPeriod;
        let isYYYYMM = !!(startP && startP.includes('-'));

        // Month-only fields
        if (startP === undefined && record.startMonth) startP = record.startMonth;
        if (endP === undefined && record.endMonth) endP = record.endMonth;

        // Fallback
        if (startP === undefined) {
            const p = parsePeriod(record.item);
            if (p) {
                startP = p.start.toString();
                endP = p.end.toString();
            }
        }

        if (!startP) return;

        const monthsCount = getTotalMonthsInRange(startP, endP);
        const monthlyAmount = record.amount / monthsCount;
        const recognizedMonths = getRecognizedMonths(targetYear, targetMonth, startP, endP, record.date);

        const recognizedAmount = recognizedMonths * monthlyAmount;
        const remainingAmount = record.amount - recognizedAmount;

        const recordYear = record.date.split('-')[0];
        const formattedStart = isYYYYMM ? toMinguoMonth(startP) : `${toMinguoYear(recordYear)}-${startP.padStart(2, '0')}`;
        const formattedEnd = isYYYYMM ? toMinguoMonth(endP) : `${toMinguoYear(recordYear)}-${endP.padStart(2, '0')}`;

        prepaidRecords.push({
            ...record,
            periodText: `${formattedStart} ~ ${formattedEnd}`,
            total: record.amount,
            recognized: recognizedAmount,
            remaining: remainingAmount,
            monthsLeft: monthsCount - recognizedMonths,
            isYYYYMM
        });

        totalPrepaidLiability += remainingAmount;
    });

    const availableYears = Array.from(new Set(records.map(r => r.date.split('-')[0]))).sort((a, b) => b - a);

    return (
        <div>
            <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem' }}>
                <h3 style={{ fontSize: '1.5rem', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <PiggyBank size={24} color="var(--success)" /> {toMinguoYear(selectedYear)}年 {selectedMonth}月 預收收入明細表
                </h3>

                <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <div className="glass-card" style={{ padding: '0.25rem 0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <Calendar size={16} color="var(--text-muted)" />
                        <select value={selectedYear} onChange={(e) => setSelectedYear(e.target.value)} style={{ border: 'none', background: 'transparent', fontWeight: 'bold', outline: 'none' }}>
                            {availableYears.length > 0 ? (
                                availableYears.map(y => <option key={y} value={y}>{toMinguoYear(y)} 年度</option>)
                            ) : (
                                <option value={currentYear}>{toMinguoYear(currentYear)} 年度</option>
                            )}
                        </select>
                    </div>
                    <div className="glass-card" style={{ padding: '0.25rem 0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <select value={selectedMonth} onChange={(e) => setSelectedMonth(e.target.value)} style={{ border: 'none', background: 'transparent', fontWeight: 'bold', outline: 'none' }}>
                            {MONTHS.map(m => <option key={m} value={m}>{m}月份</option>)}
                        </select>
                    </div>
                </div>
            </div>

            <div className="dashboard-header" style={{ marginBottom: '2rem' }}>
                <div className="glass-card stat-card" style={{ flex: 1, background: 'linear-gradient(135deg, #10b981 0%, #3b82f6 100%)', color: 'white' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                        <PiggyBank size={32} />
                        <div>
                            <div style={{ opacity: 0.8, fontSize: '0.875rem' }}>截至 {toMinguoYear(selectedYear)}年{selectedMonth}月 預收收入餘額</div>
                            <div style={{ fontSize: '1.75rem', fontWeight: '800' }}>NT$ {Math.round(totalPrepaidLiability).toLocaleString()}</div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="glass-card">
                <div style={{ overflowX: 'auto' }}>
                    <table>
                        <thead>
                            <tr>
                                <th>收款日期</th>
                                <th>社友</th>
                                <th>項目</th>
                                <th>認列區間</th>
                                <th style={{ textAlign: 'right' }}>原始金額</th>
                                <th style={{ textAlign: 'right' }}>已認列 (累計)</th>
                                <th style={{ textAlign: 'right', color: 'var(--success)' }}>剩餘預收額</th>
                            </tr>
                        </thead>
                        <tbody>
                            {prepaidRecords.length === 0 ? (
                                <tr>
                                    <td colSpan="7" style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-muted)' }}>
                                        此期間尚無預收收入紀錄
                                    </td>
                                </tr>
                            ) : (
                                prepaidRecords.sort((a, b) => {
                                    const aZero = Math.round(a.remaining) === 0;
                                    const bZero = Math.round(b.remaining) === 0;
                                    if (aZero && !bZero) return 1;
                                    if (!aZero && bZero) return -1;
                                    return new Date(b.date) - new Date(a.date);
                                }).map(r => (
                                    <tr key={r.id} style={{ opacity: r.remaining === 0 ? 0.6 : 1 }}>
                                        <td>{toMinguoDate(r.date)}</td>
                                        <td style={{ fontWeight: '600' }}>{r.member || '-'}</td>
                                        <td>{r.item}</td>
                                        <td>
                                            <span style={{
                                                padding: '0.25rem 0.6rem',
                                                background: '#f0fdf4',
                                                color: '#16a34a',
                                                borderRadius: '1rem',
                                                fontSize: '0.75rem',
                                                fontWeight: '600'
                                            }}>
                                                {r.periodText}
                                            </span>
                                        </td>
                                        <td style={{ textAlign: 'right' }}>{Math.round(r.total).toLocaleString()}</td>
                                        <td style={{ textAlign: 'right', color: '#6366f1' }}>{Math.round(r.recognized).toLocaleString()}</td>
                                        <td style={{ textAlign: 'right', fontWeight: 'bold', color: r.remaining > 0 ? 'var(--success)' : 'var(--text-muted)' }}>
                                            {Math.round(r.remaining).toLocaleString()}
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            <div style={{ marginTop: '1.5rem', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div className="glass-card" style={{ padding: '1rem', display: 'flex', alignItems: 'start', gap: '0.75rem' }}>
                    <History size={20} color="var(--primary)" />
                    <div>
                        <div style={{ fontWeight: '700', fontSize: '0.9rem' }}>已認列 (累計)</div>
                        <p style={{ margin: '0.25rem 0 0', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                            截至 <strong>{toMinguoYear(selectedYear)}年 {selectedMonth}月</strong> 已轉入各月收支報表中的認列金額。
                        </p>
                    </div>
                </div>
                <div className="glass-card" style={{ padding: '1rem', display: 'flex', alignItems: 'start', gap: '0.75rem' }}>
                    <ArrowRight size={20} color="var(--success)" />
                    <div>
                        <div style={{ fontWeight: '700', fontSize: '0.9rem' }}>預收收入餘額</div>
                        <p style={{ margin: '0.25rem 0 0', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                            截至 <strong>{toMinguoYear(selectedYear)}年 {selectedMonth}月</strong> 尚未認列為收入的預收項餘額。
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default PrepaidIncome;

// client/src/pages/PrepaidIncome.vue
<template>
  <div>
    <div v-if="loading" class="text-center pa-12">
      <v-progress-circular indeterminate color="primary" />
    </div>
    <div v-else>
      <!-- 標題 + 年月選擇 -->
      <div class="d-flex flex-wrap justify-space-between align-center mb-6 ga-3">
        <h3 class="text-h6 font-weight-bold d-flex align-center ga-2">
          <v-icon color="success">mdi-piggy-bank</v-icon>
          {{ toMinguoYear(selectedYear) }}年 {{ selectedMonth }}月 預收收入明細表
        </h3>
        <div class="d-flex ga-2">
          <v-select v-model="selectedYear" :items="availableYears" :item-title="y => toMinguoYear(y) + ' 年度'" :item-value="y => y" density="compact" variant="outlined" hide-details style="min-width:120px" />
          <v-select v-model="selectedMonth" :items="months" :item-title="m => m + '月份'" :item-value="m => m" density="compact" variant="outlined" hide-details style="min-width:100px" />
        </div>
      </div>

      <!-- 統計卡片 -->
      <v-card class="mb-6" elevation="0" rounded="lg" style="background:linear-gradient(135deg,#10b981,#3b82f6)">
        <v-card-text class="text-white d-flex align-center ga-4">
          <v-icon size="40">mdi-piggy-bank</v-icon>
          <div>
            <div style="opacity:.8" class="text-body-2">截至 {{ toMinguoYear(selectedYear) }}年{{ selectedMonth }}月 預收收入餘額</div>
            <div class="text-h5 font-weight-bold">NT$ {{ Math.round(totalLiability).toLocaleString() }}</div>
          </div>
        </v-card-text>
      </v-card>

      <!-- 明細表 -->
      <v-card elevation="1">
        <div style="overflow-x:auto">
          <v-table density="compact">
            <thead>
              <tr>
                <th>收款日期</th>
                <th>社友</th>
                <th>項目</th>
                <th>認列區間</th>
                <th class="text-right">原始金額</th>
                <th class="text-right">已認列（累計）</th>
                <th class="text-right text-success">剩餘預收額</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="prepaidRows.length === 0">
                <td colspan="7" class="text-center text-medium-emphasis pa-12">此期間尚無預收收入紀錄</td>
              </tr>
              <tr v-for="r in prepaidRows" :key="r.id" :style="{ opacity: r.remaining === 0 ? 0.55 : 1 }">
                <td>{{ toMinguoDate(r.date) }}</td>
                <td class="font-weight-medium">{{ r.member || '-' }}</td>
                <td>{{ r.item }}</td>
                <td><v-chip size="x-small" color="success" variant="tonal">{{ r.periodText }}</v-chip></td>
                <td class="text-right">{{ Math.round(r.total).toLocaleString() }}</td>
                <td class="text-right text-primary">{{ Math.round(r.recognized).toLocaleString() }}</td>
                <td class="text-right font-weight-bold" :class="r.remaining > 0 ? 'text-success' : 'text-medium-emphasis'">
                  {{ Math.round(r.remaining).toLocaleString() }}
                </td>
              </tr>
            </tbody>
          </v-table>
        </div>
      </v-card>

      <!-- 說明 -->
      <v-row class="mt-4">
        <v-col cols="12" md="6">
          <v-card elevation="0" variant="tonal" color="primary" class="pa-3">
            <div class="d-flex ga-2">
              <v-icon>mdi-history</v-icon>
              <div>
                <div class="font-weight-bold text-body-2">已認列（累計）</div>
                <p class="text-caption text-medium-emphasis mb-0">截至 <strong>{{ toMinguoYear(selectedYear) }}年 {{ selectedMonth }}月</strong> 已轉入各月收支報表中的認列金額。</p>
              </div>
            </div>
          </v-card>
        </v-col>
        <v-col cols="12" md="6">
          <v-card elevation="0" variant="tonal" color="success" class="pa-3">
            <div class="d-flex ga-2">
              <v-icon>mdi-arrow-right</v-icon>
              <div>
                <div class="font-weight-bold text-body-2">預收收入餘額</div>
                <p class="text-caption text-medium-emphasis mb-0">截至 <strong>{{ toMinguoYear(selectedYear) }}年 {{ selectedMonth }}月</strong> 尚未認列為收入的預收項餘額。</p>
              </div>
            </div>
          </v-card>
        </v-col>
      </v-row>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, inject } from 'vue'

const records = inject('records')
const loading = inject('loading')

const months = Array.from({ length: 12 }, (_, i) => i + 1)
const currentYear = new Date().getFullYear().toString()

const selectedYear = ref(currentYear)
const selectedMonth = ref(new Date().getMonth() + 1)

function toMinguoYear(y) { return parseInt(y) - 1911 }
function toMinguoDate(s) {
  if (!s) return ''
  const [y, m, d] = s.split('-')
  return `${toMinguoYear(y)}-${m}-${d}`
}
function toMinguoMonth(s) {
  if (!s || !s.includes('-')) return s
  const [y, m] = s.split('-')
  return `${toMinguoYear(y)}-${m}`
}
function parsePeriod(item) {
  const match = item.match(/(\d+)-(\d+)月/)
  return match ? { start: parseInt(match[1]), end: parseInt(match[2]) } : null
}
function getTotalMonths(startP, endP) {
  if (!startP || !endP) return 1
  if (startP.includes('-')) {
    const [sY, sM] = startP.split('-').map(Number)
    const [eY, eM] = endP.split('-').map(Number)
    return (eY - sY) * 12 + (eM - sM) + 1
  }
  return parseInt(endP) - parseInt(startP) + 1
}
function getRecognizedMonths(tY, tM, startP, endP, recordDate) {
  if (!startP || !endP) return 0
  const targetStr = `${tY}-${tM.toString().padStart(2, '0')}`
  const total = getTotalMonths(startP, endP)
  if (startP.includes('-')) {
    if (targetStr < startP) return 0
    if (targetStr >= endP) return total
    const [sY, sM] = startP.split('-').map(Number)
    return (tY - sY) * 12 + (tM - sM) + 1
  } else {
    const recYear = parseInt(recordDate.split('-')[0])
    if (tY < recYear) return 0
    if (tY > recYear) return total
    return Math.max(0, Math.min(total, tM - parseInt(startP) + 1))
  }
}

const availableYears = computed(() =>
  [...new Set((records.value || []).map(r => r.date.split('-')[0]))].sort((a, b) => b - a)
)

const prepaidRows = computed(() => {
  const tY = parseInt(selectedYear.value), tM = parseInt(selectedMonth.value)
  const rows = []
  ;(records.value || []).filter(r => r.type === 'income').forEach(r => {
    let startP = r.startPeriod, endP = r.endPeriod
    const isYYYYMM = !!(startP && startP.includes('-'))
    if (startP === undefined && r.startMonth) startP = r.startMonth
    if (endP === undefined && r.endMonth) endP = r.endMonth
    if (startP === undefined) {
      const p = parsePeriod(r.item)
      if (p) { startP = p.start.toString(); endP = p.end.toString() }
    }
    if (!startP) return
    const monthsCount = getTotalMonths(startP, endP)
    const monthly = r.amount / monthsCount
    const recognized = getRecognizedMonths(tY, tM, startP, endP, r.date) * monthly
    const remaining = r.amount - recognized
    const rYear = r.date.split('-')[0]
    const fStart = isYYYYMM ? toMinguoMonth(startP) : `${toMinguoYear(rYear)}-${startP.padStart(2,'0')}`
    const fEnd = isYYYYMM ? toMinguoMonth(endP) : `${toMinguoYear(rYear)}-${endP.padStart(2,'0')}`
    rows.push({ ...r, periodText: `${fStart} ~ ${fEnd}`, total: r.amount, recognized, remaining })
  })
  return rows.sort((a, b) => {
    const aZ = Math.round(a.remaining) === 0, bZ = Math.round(b.remaining) === 0
    if (aZ !== bZ) return aZ ? 1 : -1
    return new Date(b.date) - new Date(a.date)
  })
})

const totalLiability = computed(() => prepaidRows.value.reduce((s, r) => s + r.remaining, 0))
</script>
