// client/src/pages/TransferForm.vue
<template>
  <v-card max-width="600" class="mx-auto" elevation="1">
    <v-card-title class="d-flex justify-space-between align-center pa-4">
      <div class="d-flex align-center ga-2">
        <v-icon color="primary">mdi-swap-horizontal</v-icon>
        <span class="text-h6 font-weight-bold">{{ editingRecord ? '編輯調撥單' : '填寫調撥單' }}</span>
      </div>
      <v-btn v-if="editingRecord" icon variant="tonal" size="small" @click="handleCancelEdit">
        <v-icon>mdi-close</v-icon>
      </v-btn>
    </v-card-title>

    <v-card-text>
      <v-form @submit.prevent="handleSubmit">
        <v-text-field v-model="formData.date" label="調撥日期" type="date" density="compact" variant="outlined" required class="mb-3" />

        <v-row align="center" class="mb-3">
          <v-col cols="5">
            <v-select v-model="formData.fromAccount" label="轉出帳戶" :items="ACCOUNTS" density="compact" variant="outlined" required />
          </v-col>
          <v-col cols="2" class="text-center">
            <v-icon>mdi-arrow-right</v-icon>
          </v-col>
          <v-col cols="5">
            <v-select v-model="formData.toAccount" label="轉入帳戶" :items="ACCOUNTS" density="compact" variant="outlined" required />
          </v-col>
        </v-row>

        <v-text-field
          v-model="formData.amount"
          label="調撥金額 (NT$)"
          type="number"
          density="compact"
          variant="outlined"
          required
          class="mb-2"
        />

        <v-textarea
          v-model="formData.remark"
          label="備註說明"
          placeholder="例如：提款支應、帳戶互轉..."
          rows="3"
          density="compact"
          variant="outlined"
          class="mb-4"
        />

        <div class="d-flex ga-3">
          <v-btn type="submit" color="primary" variant="flat" prepend-icon="mdi-content-save" class="flex-grow-1">
            {{ editingRecord ? '更新調撥' : '儲存調撥' }}
          </v-btn>
          <v-btn v-if="editingRecord" color="blue-grey" variant="flat" prepend-icon="mdi-delete" @click="handleDelete">刪除</v-btn>
          <v-btn v-if="editingRecord" variant="tonal" @click="handleCancelEdit">取消</v-btn>
        </div>
      </v-form>
    </v-card-text>
  </v-card>
</template>

<script setup>
import { ref, watch, inject } from 'vue'

const editingRecord = inject('editingRecord')
const addRecord = inject('addRecord')
const updateRecord = inject('updateRecord')
const deleteRecord = inject('deleteRecord')
const handleCancelEdit = inject('handleCancelEdit')

const ACCOUNTS = ['淑華代收付', '一銀帳戶', '社長代收付']

function makeDefaultForm() {
  return {
    date: new Date().toISOString().split('T')[0],
    fromAccount: '淑華代收付',
    toAccount: '一銀帳戶',
    amount: '',
    remark: '',
  }
}

const formData = ref(makeDefaultForm())

watch(editingRecord, (ed) => {
  if (ed) {
    formData.value = {
      date: ed.date,
      fromAccount: ed.fromAccount || '淑華代收付',
      toAccount: ed.toAccount || '一銀帳戶',
      amount: ed.amount,
      remark: ed.remark || '',
    }
  }
}, { immediate: true })

async function handleSubmit() {
  if (!formData.value.amount || parseFloat(formData.value.amount) <= 0) {
    alert('請輸入有效金額')
    return
  }
  if (formData.value.fromAccount === formData.value.toAccount) {
    alert('轉出帳戶與轉入帳戶不能相同')
    return
  }
  const payload = {
    ...formData.value,
    item: `資金調撥: ${formData.value.fromAccount} ➡ ${formData.value.toAccount}`,
    type: 'transfer',
    amount: parseFloat(formData.value.amount),
  }
  if (editingRecord.value) {
    await updateRecord(editingRecord.value.id, payload)
  } else {
    await addRecord(payload)
    formData.value = makeDefaultForm()
  }
}

async function handleDelete() {
  if (editingRecord.value) await deleteRecord(editingRecord.value.id)
}
</script>

// client/src/pages/TransferForm.jsx
import React, { useState, useEffect } from 'react';
import { Save, RefreshCw, X, Trash2, Calendar, ArrowRight } from 'lucide-react';

function TransferForm({ onAdd, onUpdate, onDelete, editData, onCancel }) {
    const ACCOUNTS = ['淑華代收付', '一銀帳戶', '社長代收付'];

    const [formData, setFormData] = useState({
        date: new Date().toISOString().split('T')[0],
        fromAccount: '淑華代收付',
        toAccount: '一銀帳戶',
        amount: '',
        remark: ''
    });

    useEffect(() => {
        if (editData) {
            setFormData({
                date: editData.date,
                fromAccount: editData.fromAccount || '淑華代收付',
                toAccount: editData.toAccount || '一銀帳戶',
                amount: editData.amount,
                remark: editData.remark || ''
            });
        }
    }, [editData]);

    const handleSubmit = (e) => {
        e.preventDefault();

        if (!formData.amount || parseFloat(formData.amount) <= 0) {
            alert('請輸入有效金額');
            return;
        }

        if (formData.fromAccount === formData.toAccount) {
            alert('轉出帳戶與轉入帳戶不能相同');
            return;
        }

        const payload = {
            ...formData,
            item: `資金調撥: ${formData.fromAccount} ➡ ${formData.toAccount}`,
            type: 'transfer',
            amount: parseFloat(formData.amount)
        };

        if (editData) {
            onUpdate(editData.id, payload);
        } else {
            onAdd(payload);
        }

        if (!editData) {
            setFormData({
                date: new Date().toISOString().split('T')[0],
                fromAccount: '淑華代收付',
                toAccount: '一銀帳戶',
                amount: '',
                remark: ''
            });
        }
    };

    return (
        <div className="glass-card" style={{ maxWidth: '600px', margin: '0 auto' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                    <RefreshCw size={24} color="var(--primary)" />
                    <h3 style={{ fontSize: '1.5rem', fontWeight: '700' }}>
                        {editData ? '編輯調撥單' : '填寫調撥單'}
                    </h3>
                </div>
                {editData && (
                    <button onClick={onCancel} style={{ background: '#e2e8f0', color: 'var(--text-main)', padding: '0.5rem' }}>
                        <X size={18} />
                    </button>
                )}
            </div>

            <form onSubmit={handleSubmit}>
                <div className="form-group">
                    <label>調撥日期</label>
                    <input
                        type="date"
                        value={formData.date}
                        onChange={e => setFormData({ ...formData, date: e.target.value })}
                        required
                    />
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem' }}>
                    <div className="form-group" style={{ marginBottom: 0 }}>
                        <label>轉出帳戶</label>
                        <select
                            value={formData.fromAccount}
                            onChange={e => setFormData({ ...formData, fromAccount: e.target.value })}
                            required
                        >
                            {ACCOUNTS.map(acc => <option key={acc} value={acc}>{acc}</option>)}
                        </select>
                    </div>
                    <div style={{ paddingTop: '1.5rem' }}>
                        <ArrowRight size={24} color="#94a3b8" />
                    </div>
                    <div className="form-group" style={{ marginBottom: 0 }}>
                        <label>轉入帳戶</label>
                        <select
                            value={formData.toAccount}
                            onChange={e => setFormData({ ...formData, toAccount: e.target.value })}
                            required
                        >
                            {ACCOUNTS.map(acc => <option key={acc} value={acc}>{acc}</option>)}
                        </select>
                    </div>
                </div>

                <div className="form-group">
                    <label>調撥金額 (NT$)</label>
                    <input
                        type="number"
                        placeholder="請輸入調撥金額"
                        value={formData.amount}
                        onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                        required
                    />
                </div>

                <div className="form-group">
                    <label>備註說明</label>
                    <textarea
                        rows="3"
                        placeholder="例如：提款支應、帳戶互轉..."
                        value={formData.remark}
                        onChange={(e) => setFormData({ ...formData, remark: e.target.value })}
                    ></textarea>
                </div>

                <div style={{ display: 'flex', gap: '1rem' }}>
                    <button type="submit" style={{ flex: 1, display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '0.5rem', background: 'var(--primary)' }}>
                        <Save size={18} /> {editData ? '更新調撥' : '儲存調撥'}
                    </button>
                    {editData && (
                        <button
                            type="button"
                            onClick={() => onDelete(editData.id)}
                            style={{ background: '#475569', display: 'flex', alignItems: 'center', gap: '0.5rem' }}
                        >
                            <Trash2 size={18} /> 刪除
                        </button>
                    )}
                    {editData && (
                        <button type="button" onClick={onCancel} style={{ background: '#94a3b8' }}>
                            取消
                        </button>
                    )}
                </div>
            </form>
        </div>
    );
}

export default TransferForm;
